name: Terraform Plan

on:
  pull_request:
    branches:
      - main      # Executa para o ambiente "prod" em pull requests para a branch main
      - dev   # Executa para o ambiente "dev" em pull requests para a branch develop

jobs:
  terraform:
    name: Run Terraform Plan
    runs-on: ubuntu-latest

    # Configura o ambiente dinamicamente, dependendo da branch
    environment:
      name: ${{ github.event.pull_request.base.ref == 'main' && 'prod' || 'dev' }}

    # Definir as credenciais da AWS com base no ambiente (dev ou prod)
    env:
      AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.9.5

      - name: Terraform Init
        run: terraform init  # Executa terraform init na raiz do projeto

      - name: Terraform Plan
        run: terraform plan  # Executa terraform plan na raiz do projeto
