name: Terraform Apply

on:
  workflow_dispatch:  # Permite execução manual
  workflow_run:
    workflows: ["Terraform Plan"]  # Dependência do workflow de plan
    types:
      - completed

jobs:
  apply:
    runs-on: ubuntu-latest
    # Configura o ambiente dinamicamente, dependendo da branch
    environment:
        name: ${{ github.event.pull_request.base.ref == 'main' && 'prod' || 'dev' }}
  
    # Definir as credenciais da AWS com base no ambiente (dev ou prod)
    env:
      AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.9.5

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve  # Executa apply
